// Implementation file for parser generated by fsyacc
module Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"

    open LanguageAST
    open DataAST

# 11 "WarewolfLanguage.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | STRING of (string)
  | FLOAT of (float)
  | INT of (int)
  | OPENLANGUAGE
  | CLOSELANGAUGE
  | OPENBRACKET
  | CLOSEDBRACKET
  | STAR
  | DOT
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_STRING
    | TOKEN_FLOAT
    | TOKEN_INT
    | TOKEN_OPENLANGUAGE
    | TOKEN_CLOSELANGAUGE
    | TOKEN_OPENBRACKET
    | TOKEN_CLOSEDBRACKET
    | TOKEN_STAR
    | TOKEN_DOT
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_langExpression
    | NONTERM_variableExpression
    | NONTERM_recset
    | NONTERM_recsetName
    | NONTERM_index
    | NONTERM_scalar
    | NONTERM_atom

// This function maps tokens to integers indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | STRING _ -> 1 
  | FLOAT _ -> 2 
  | INT _ -> 3 
  | OPENLANGUAGE  -> 4 
  | CLOSELANGAUGE  -> 5 
  | OPENBRACKET  -> 6 
  | CLOSEDBRACKET  -> 7 
  | STAR  -> 8 
  | DOT  -> 9 

// This function maps integers indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_STRING 
  | 2 -> TOKEN_FLOAT 
  | 3 -> TOKEN_INT 
  | 4 -> TOKEN_OPENLANGUAGE 
  | 5 -> TOKEN_CLOSELANGAUGE 
  | 6 -> TOKEN_OPENBRACKET 
  | 7 -> TOKEN_CLOSEDBRACKET 
  | 8 -> TOKEN_STAR 
  | 9 -> TOKEN_DOT 
  | 12 -> TOKEN_end_of_input
  | 10 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_langExpression 
    | 3 -> NONTERM_langExpression 
    | 4 -> NONTERM_langExpression 
    | 5 -> NONTERM_langExpression 
    | 6 -> NONTERM_langExpression 
    | 7 -> NONTERM_langExpression 
    | 8 -> NONTERM_langExpression 
    | 9 -> NONTERM_langExpression 
    | 10 -> NONTERM_langExpression 
    | 11 -> NONTERM_langExpression 
    | 12 -> NONTERM_langExpression 
    | 13 -> NONTERM_variableExpression 
    | 14 -> NONTERM_variableExpression 
    | 15 -> NONTERM_variableExpression 
    | 16 -> NONTERM_variableExpression 
    | 17 -> NONTERM_variableExpression 
    | 18 -> NONTERM_recset 
    | 19 -> NONTERM_recset 
    | 20 -> NONTERM_recsetName 
    | 21 -> NONTERM_index 
    | 22 -> NONTERM_index 
    | 23 -> NONTERM_scalar 
    | 24 -> NONTERM_atom 
    | 25 -> NONTERM_atom 
    | 26 -> NONTERM_atom 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 12 
let _fsyacc_tagOfErrorTerminal = 10

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | STRING _ -> "STRING" 
  | FLOAT _ -> "FLOAT" 
  | INT _ -> "INT" 
  | OPENLANGUAGE  -> "OPENLANGUAGE" 
  | CLOSELANGAUGE  -> "CLOSELANGAUGE" 
  | OPENBRACKET  -> "OPENBRACKET" 
  | CLOSEDBRACKET  -> "CLOSEDBRACKET" 
  | STAR  -> "STAR" 
  | DOT  -> "DOT" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | STRING _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | FLOAT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | INT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | OPENLANGUAGE  -> (null : System.Object) 
  | CLOSELANGAUGE  -> (null : System.Object) 
  | OPENBRACKET  -> (null : System.Object) 
  | CLOSEDBRACKET  -> (null : System.Object) 
  | STAR  -> (null : System.Object) 
  | DOT  -> (null : System.Object) 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 3us; 65535us; 0us; 2us; 2us; 15us; 15us; 15us; 3us; 65535us; 0us; 7us; 2us; 8us; 15us; 8us; 3us; 65535us; 0us; 5us; 2us; 5us; 15us; 5us; 3us; 65535us; 0us; 6us; 2us; 6us; 15us; 6us; 1us; 65535us; 18us; 19us; 3us; 65535us; 0us; 4us; 2us; 4us; 15us; 4us; 3us; 65535us; 0us; 3us; 2us; 3us; 15us; 3us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 7us; 11us; 15us; 19us; 21us; 25us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 2us; 1us; 13us; 2us; 2us; 14us; 2us; 3us; 15us; 2us; 4us; 16us; 1us; 5us; 1us; 6us; 2us; 6us; 13us; 5us; 7us; 18us; 19us; 20us; 23us; 1us; 8us; 1us; 9us; 1us; 10us; 1us; 11us; 1us; 12us; 1us; 13us; 1us; 17us; 4us; 18us; 19us; 20us; 23us; 3us; 18us; 19us; 20us; 1us; 18us; 1us; 18us; 1us; 18us; 1us; 18us; 1us; 18us; 2us; 19us; 20us; 1us; 19us; 1us; 19us; 1us; 19us; 1us; 21us; 1us; 22us; 1us; 23us; 1us; 24us; 1us; 25us; 1us; 26us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 7us; 10us; 13us; 16us; 18us; 20us; 23us; 29us; 31us; 33us; 35us; 37us; 39us; 41us; 43us; 48us; 52us; 54us; 56us; 58us; 60us; 62us; 65us; 67us; 69us; 71us; 73us; 75us; 77us; 79us; 81us; |]
let _fsyacc_action_rows = 34
let _fsyacc_actionTableElements = [|10us; 32768us; 0us; 16us; 1us; 33us; 2us; 31us; 3us; 32us; 4us; 9us; 5us; 10us; 6us; 11us; 7us; 12us; 8us; 13us; 9us; 14us; 0us; 49152us; 10us; 16385us; 0us; 16us; 1us; 33us; 2us; 31us; 3us; 32us; 4us; 9us; 5us; 10us; 6us; 11us; 7us; 12us; 8us; 13us; 9us; 14us; 0us; 16386us; 0us; 16387us; 0us; 16388us; 0us; 16389us; 0us; 16390us; 1us; 16390us; 12us; 16397us; 1us; 16391us; 1us; 17us; 0us; 16392us; 0us; 16393us; 0us; 16394us; 0us; 16395us; 0us; 16396us; 10us; 32768us; 0us; 16us; 1us; 33us; 2us; 31us; 3us; 32us; 4us; 9us; 5us; 10us; 6us; 11us; 7us; 12us; 8us; 13us; 9us; 14us; 0us; 16401us; 2us; 32768us; 5us; 30us; 6us; 18us; 3us; 32768us; 3us; 29us; 7us; 24us; 8us; 28us; 1us; 32768us; 7us; 20us; 1us; 32768us; 9us; 21us; 1us; 32768us; 1us; 22us; 1us; 32768us; 5us; 23us; 0us; 16402us; 1us; 16404us; 9us; 25us; 1us; 32768us; 1us; 26us; 1us; 32768us; 5us; 27us; 0us; 16403us; 0us; 16405us; 0us; 16406us; 0us; 16407us; 0us; 16408us; 0us; 16409us; 0us; 16410us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 11us; 12us; 23us; 24us; 25us; 26us; 27us; 28us; 30us; 32us; 33us; 34us; 35us; 36us; 37us; 48us; 49us; 52us; 56us; 58us; 60us; 62us; 64us; 65us; 67us; 69us; 71us; 72us; 73us; 74us; 75us; 76us; 77us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 2us; 1us; 1us; 1us; 1us; 8us; 7us; 4us; 1us; 1us; 3us; 1us; 1us; 1us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 3us; 3us; 3us; 3us; 3us; 4us; 4us; 5us; 6us; 6us; 7us; 8us; 8us; 8us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 65535us; 65535us; 65535us; 16389us; 16390us; 65535us; 65535us; 16392us; 16393us; 16394us; 16395us; 16396us; 65535us; 16401us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16402us; 65535us; 65535us; 65535us; 16403us; 16405us; 16406us; 16407us; 16408us; 16409us; 16410us; |]
let _fsyacc_reductions ()  =    [| 
# 154 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : LanguageAST.LanguageExpression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 163 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : LanguageAST.LanguageExpression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 30 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                            _1
                   )
# 30 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : LanguageAST.LanguageExpression));
# 174 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : DataAST.Atom)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                              AtomExpression _1
                   )
# 33 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : LanguageAST.LanguageExpression));
# 185 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : LanguageAST.ScalarIdentifier)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                  ScalarExpression _1 
                   )
# 34 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : LanguageAST.LanguageExpression));
# 196 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : LanguageAST.RecordSetIdentifier)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 35 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                 RecordSetExpression _1 
                   )
# 35 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : LanguageAST.LanguageExpression));
# 207 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'recsetName)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                     RecordSetNameExpression _1 
                   )
# 36 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : LanguageAST.LanguageExpression));
# 218 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'variableExpression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                             ComplexExpression _1 
                   )
# 37 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : LanguageAST.LanguageExpression));
# 229 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                      AtomExpression (DataString "[[")
                   )
# 38 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : LanguageAST.LanguageExpression));
# 239 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                       AtomExpression (DataString "]]")
                   )
# 39 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : LanguageAST.LanguageExpression));
# 249 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 40 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                     AtomExpression (DataString "(")
                   )
# 40 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : LanguageAST.LanguageExpression));
# 259 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 41 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                       AtomExpression (DataString ")")
                   )
# 41 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : LanguageAST.LanguageExpression));
# 269 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 42 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                              AtomExpression (DataString "*")
                   )
# 42 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : LanguageAST.LanguageExpression));
# 279 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 43 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                             AtomExpression (DataString ".")
                   )
# 43 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : LanguageAST.LanguageExpression));
# 289 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : LanguageAST.LanguageExpression)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'variableExpression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 45 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                                                 _1::_2
                   )
# 45 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : 'variableExpression));
# 301 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : DataAST.Atom)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 46 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                              [AtomExpression _1]
                   )
# 46 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : 'variableExpression));
# 312 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : LanguageAST.ScalarIdentifier)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 47 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                  [ScalarExpression _1] 
                   )
# 47 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : 'variableExpression));
# 323 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : LanguageAST.RecordSetIdentifier)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 48 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                 [RecordSetExpression _1] 
                   )
# 48 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : 'variableExpression));
# 334 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 49 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                             []
                   )
# 49 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : 'variableExpression));
# 344 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'index)) in
            let _7 = (let data = parseState.GetInput(7) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 51 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                                                                                        {Name = _2; Column = _7; Index =_4 ;}
                   )
# 51 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : LanguageAST.RecordSetIdentifier));
# 357 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _6 = (let data = parseState.GetInput(6) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 52 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                                                                                  {Name = _2; Column = _6; Index =Last ;}
                   )
# 52 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : LanguageAST.RecordSetIdentifier));
# 369 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 54 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                                                        {Name = _2;}
                   )
# 54 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : 'recsetName));
# 380 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 56 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                               Star 
                   )
# 56 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : 'index));
# 390 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 57 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                             IntIndex _1
                   )
# 57 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : 'index));
# 401 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 59 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                                          _2
                   )
# 59 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : LanguageAST.ScalarIdentifier));
# 412 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : float)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 61 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                  Float _1 
                   )
# 61 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : DataAST.Atom));
# 423 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 62 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                               Int _1 
                   )
# 62 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : DataAST.Atom));
# 434 "WarewolfLanguage.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 63 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                                  DataString _1 
                   )
# 63 "..\WarewolfLanguageParser\WarewolfLanguage.fsy"
                 : DataAST.Atom));
|]
# 446 "WarewolfLanguage.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 13;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : LanguageAST.LanguageExpression =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
